//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMngVSIX.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTMngVSIX.Resource.Lang.ContextMenu", typeof(ContextMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to AI Server.
        /// </summary>
        internal static string Button_C0000_Connect_Server {
            get {
                return ResourceManager.GetString("Button_C0000_Connect_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        internal static string Button_C1000_GenerateCode {
            get {
                return ResourceManager.GetString("Button_C1000_GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Function.
        /// </summary>
        internal static string Button_C1001_GenerateFunction {
            get {
                return ResourceManager.GetString("Button_C1001_GenerateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Class.
        /// </summary>
        internal static string Button_C1002_GenerateClass {
            get {
                return ResourceManager.GetString("Button_C1002_GenerateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor Code.
        /// </summary>
        internal static string Button_C1003_ReflectCode {
            get {
                return ResourceManager.GetString("Button_C1003_ReflectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fill Middle Block.
        /// </summary>
        internal static string Button_C1004_FillInMiddle {
            get {
                return ResourceManager.GetString("Button_C1004_FillInMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comments.
        /// </summary>
        internal static string Button_C1005_AddComment {
            get {
                return ResourceManager.GetString("Button_C1005_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Function.
        /// </summary>
        internal static string Button_C1006_CompleteFunction {
            get {
                return ResourceManager.GetString("Button_C1006_CompleteFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Function Summary.
        /// </summary>
        internal static string Button_C1040_SummaryFunction {
            get {
                return ResourceManager.GetString("Button_C1040_SummaryFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize Function.
        /// </summary>
        internal static string Button_C1050_OptimizeFunction {
            get {
                return ResourceManager.GetString("Button_C1050_OptimizeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain Function.
        /// </summary>
        internal static string Button_C1060_ExplainFunction {
            get {
                return ResourceManager.GetString("Button_C1060_ExplainFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Documentation from Selection.
        /// </summary>
        internal static string Button_C2000_DocsSelection {
            get {
                return ResourceManager.GetString("Button_C2000_DocsSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Function Documentation.
        /// </summary>
        internal static string Button_C2001_DocsFunction {
            get {
                return ResourceManager.GetString("Button_C2001_DocsFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Class Documentation.
        /// </summary>
        internal static string Button_C2002_DocsClass {
            get {
                return ResourceManager.GetString("Button_C2002_DocsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate API Documentation.
        /// </summary>
        internal static string Button_C2010_DocsApi {
            get {
                return ResourceManager.GetString("Button_C2010_DocsApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Technical Specification.
        /// </summary>
        internal static string Button_C2020_DocsTechnicalSpecifications {
            get {
                return ResourceManager.GetString("Button_C2020_DocsTechnicalSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain Error.
        /// </summary>
        internal static string Button_C3010_ExplainError {
            get {
                return ResourceManager.GetString("Button_C3010_ExplainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Fix.
        /// </summary>
        internal static string Button_C3020_SuggestFixes {
            get {
                return ResourceManager.GetString("Button_C3020_SuggestFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the error line.
        /// </summary>
        internal static string Button_C3030_FixErrorLine {
            get {
                return ResourceManager.GetString("Button_C3030_FixErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate White-box Test Cases.
        /// </summary>
        internal static string Button_C4010_Whitebox {
            get {
                return ResourceManager.GetString("Button_C4010_Whitebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Black-box Unit Test Cases.
        /// </summary>
        internal static string Button_C4020_Blackbox_UnitTests {
            get {
                return ResourceManager.GetString("Button_C4020_Blackbox_UnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Black-box Integration Test Cases.
        /// </summary>
        internal static string Button_C4021_Backbox_IntegrationTests {
            get {
                return ResourceManager.GetString("Button_C4021_Backbox_IntegrationTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Black-box Edge Case Test Cases.
        /// </summary>
        internal static string Button_C4022_Blackbox_EdgeCaseTesting {
            get {
                return ResourceManager.GetString("Button_C4022_Blackbox_EdgeCaseTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Black-box Performance Test Cases.
        /// </summary>
        internal static string Button_C4023_Blackbox_PerformanceTesting {
            get {
                return ResourceManager.GetString("Button_C4023_Blackbox_PerformanceTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Code Function.
        /// </summary>
        internal static string Button_C5020_ReviewCodeFunction {
            get {
                return ResourceManager.GetString("Button_C5020_ReviewCodeFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Code Class.
        /// </summary>
        internal static string Button_C5021_ReviewCodeClass {
            get {
                return ResourceManager.GetString("Button_C5021_ReviewCodeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Solution.
        /// </summary>
        internal static string Button_C5030_SuggestSolution {
            get {
                return ResourceManager.GetString("Button_C5030_SuggestSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Deploy.
        /// </summary>
        internal static string Button_C5040_SuggestDeploy {
            get {
                return ResourceManager.GetString("Button_C5040_SuggestDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Architecture.
        /// </summary>
        internal static string Button_C5050_SuggestArchitecture {
            get {
                return ResourceManager.GetString("Button_C5050_SuggestArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Technologies.
        /// </summary>
        internal static string Button_C5060_SuggestTechnologies {
            get {
                return ResourceManager.GetString("Button_C5060_SuggestTechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest Features.
        /// </summary>
        internal static string Button_C5070_SuggestFeatures {
            get {
                return ResourceManager.GetString("Button_C5070_SuggestFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Code Snippet.
        /// </summary>
        internal static string Button_C6010_AddCodeSnippet {
            get {
                return ResourceManager.GetString("Button_C6010_AddCodeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Code Snippet.
        /// </summary>
        internal static string Button_C6011_ResetCodeSnippet {
            get {
                return ResourceManager.GetString("Button_C6011_ResetCodeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Architect.
        /// </summary>
        internal static string MenuGroup_AI_Architect {
            get {
                return ResourceManager.GetString("MenuGroup_AI_Architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Coding.
        /// </summary>
        internal static string MenuGroup_AI_Coding {
            get {
                return ResourceManager.GetString("MenuGroup_AI_Coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Docs.
        /// </summary>
        internal static string MenuGroup_AI_Docs {
            get {
                return ResourceManager.GetString("MenuGroup_AI_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Testing.
        /// </summary>
        internal static string MenuGroup_AI_Testing {
            get {
                return ResourceManager.GetString("MenuGroup_AI_Testing", resourceCulture);
            }
        }
    }
}
