//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMngVSIX.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTMngVSIX.Resource.Lang.DebugInfo", typeof(DebugInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Information.
        /// </summary>
        internal static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Last_Receive_Id {
            get {
                return ResourceManager.GetString("Last_Receive_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Last_Receive_Model {
            get {
                return ResourceManager.GetString("Last_Receive_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string Last_Receive_Provider {
            get {
                return ResourceManager.GetString("Last_Receive_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive data.
        /// </summary>
        internal static string Last_Receive_Title {
            get {
                return ResourceManager.GetString("Last_Receive_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        internal static string Last_Send_Endpoint {
            get {
                return ResourceManager.GetString("Last_Send_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Last_Send_Model {
            get {
                return ResourceManager.GetString("Last_Send_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent data.
        /// </summary>
        internal static string Last_Send_Title {
            get {
                return ResourceManager.GetString("Last_Send_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last send and receive.
        /// </summary>
        internal static string Last_Title {
            get {
                return ResourceManager.GetString("Last_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Tokens details.
        /// </summary>
        internal static string Session_Input_Tokens_Details {
            get {
                return ResourceManager.GetString("Session_Input_Tokens_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Tokens details.
        /// </summary>
        internal static string Session_Output_Tokens_Details {
            get {
                return ResourceManager.GetString("Session_Output_Tokens_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session start time.
        /// </summary>
        internal static string Session_Time {
            get {
                return ResourceManager.GetString("Session_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string Session_Title {
            get {
                return ResourceManager.GetString("Session_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of Input Tokens.
        /// </summary>
        internal static string Session_Total_Number_Of_Input_Tokens {
            get {
                return ResourceManager.GetString("Session_Total_Number_Of_Input_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of Output Tokens.
        /// </summary>
        internal static string Session_Total_Number_Of_Output_Token {
            get {
                return ResourceManager.GetString("Session_Total_Number_Of_Output_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number Of Tokens.
        /// </summary>
        internal static string Session_Total_Number_Of_Tokens {
            get {
                return ResourceManager.GetString("Session_Total_Number_Of_Tokens", resourceCulture);
            }
        }
    }
}
