//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMngVSIX.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormOption {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormOption() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTMngVSIX.Resource.Lang.FormOption", typeof(FormOption).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently open document file.
        /// </summary>
        public static string Option_ActiveDocument {
            get {
                return ResourceManager.GetString("Option_ActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error information.
        /// </summary>
        public static string Option_Error {
            get {
                return ResourceManager.GetString("Option_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently opened function (Fill In Middle format).
        /// </summary>
        public static string Option_FillInMiddle {
            get {
                return ResourceManager.GetString("Option_FillInMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information includes.
        /// </summary>
        public static string Option_LabelTitle {
            get {
                return ResourceManager.GetString("Option_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently opened class.
        /// </summary>
        public static string Option_ParentClass {
            get {
                return ResourceManager.GetString("Option_ParentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently opened function.
        /// </summary>
        public static string Option_ParentFunction {
            get {
                return ResourceManager.GetString("Option_ParentFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project directory tree.
        /// </summary>
        public static string Option_ProjectStructure {
            get {
                return ResourceManager.GetString("Option_ProjectStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected text.
        /// </summary>
        public static string Option_SelectedText {
            get {
                return ResourceManager.GetString("Option_SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution directory tree.
        /// </summary>
        public static string Option_SolutionStructure {
            get {
                return ResourceManager.GetString("Option_SolutionStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Setting.
        /// </summary>
        public static string Setting_GroupTitle {
            get {
                return ResourceManager.GetString("Setting_GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output formatting.
        /// </summary>
        public static string Setting_OutputFormat {
            get {
                return ResourceManager.GetString("Setting_OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role.
        /// </summary>
        public static string Setting_RoleLabel {
            get {
                return ResourceManager.GetString("Setting_RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Input to English.
        /// </summary>
        public static string Setting_TranslateInput {
            get {
                return ResourceManager.GetString("Setting_TranslateInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display output in the following language..
        /// </summary>
        public static string Setting_TranslateOutput {
            get {
                return ResourceManager.GetString("Setting_TranslateOutput", resourceCulture);
            }
        }
    }
}
