//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMngVSIX.Resource.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTMngVSIX.Resource.Lang.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to add?.
        /// </summary>
        public static string Input_Add {
            get {
                return ResourceManager.GetString("Input_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What architecture do you want to explore?.
        /// </summary>
        public static string Input_Architecture {
            get {
                return ResourceManager.GetString("Input_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to deploy?.
        /// </summary>
        public static string Input_Deploy {
            get {
                return ResourceManager.GetString("Input_Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string Input_EnterDescription {
            get {
                return ResourceManager.GetString("Input_EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What feature do you want to add?.
        /// </summary>
        public static string Input_Feature {
            get {
                return ResourceManager.GetString("Input_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to create it?.
        /// </summary>
        public static string Input_Generate {
            get {
                return ResourceManager.GetString("Input_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What code do you want to create?.
        /// </summary>
        public static string Input_Generate_Code {
            get {
                return ResourceManager.GetString("Input_Generate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What function do you want to create?.
        /// </summary>
        public static string Input_Generate_Function {
            get {
                return ResourceManager.GetString("Input_Generate_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to modify the code?.
        /// </summary>
        public static string Input_Modify_Code {
            get {
                return ResourceManager.GetString("Input_Modify_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to request anything else?.
        /// </summary>
        public static string Input_Request {
            get {
                return ResourceManager.GetString("Input_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What problem do you want to find a solution for?.
        /// </summary>
        public static string Input_Solution {
            get {
                return ResourceManager.GetString("Input_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested solution.
        /// </summary>
        public static string Input_Suggest_Solution {
            get {
                return ResourceManager.GetString("Input_Suggest_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What technology are you looking for?.
        /// </summary>
        public static string Input_Technology {
            get {
                return ResourceManager.GetString("Input_Technology", resourceCulture);
            }
        }
    }
}
